name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - name: Linux
            runs-on: ubuntu-latest
            run: script/bootstrap
            artifact: build/Flasher
          - name: macOS
            runs-on: macos-latest
            run: script/bootstrap
            deploy: macdeployqt
            artifact: build/Flasher.app
          - name: Windows
            runs-on: windows-latest
            run: cmake -B build && cmake --build build --config Release --parallel
            artifact: build/Release/Flasher.exe
    steps:
      - uses: actions/checkout@v3
      - uses: jurplel/install-qt-action@v3
        with:
          version: "6"
          cache: true
          modules: qtserialport
      - run: ${{ matrix.run }}
      # TODO: get this working with linuxdeployqt and windeployqt eventually
      - if: ${{ matrix.name == 'macOS' }}
        run: ${{ matrix.deploy }} ${{ matrix.artifact }}
      - uses: actions/upload-artifact@v3
        with:
          name: Flasher-${{ matrix.name }}
          path: ${{ matrix.artifact }}
          if-no-files-found: error
